### ISSUE TITLE
[ERROR]: Unexpected error occurred in scheduled task

### ISSUE THREAD

**Issue by hubecker** [micw/homedatabroker#14]
I have the following error in my log:
`2024-11-16T09:12:58.077+01:00 DEBUG 1 --- [  scheduling-12] d.w.h.metric.MetricRegistry              : pulse.phaseAngleIL3toUL3 = -1 DEGREE
2024-11-16T09:12:58.077+01:00 DEBUG 1 --- [  scheduling-12] d.w.h.metric.MetricRegistry              : pulse.networkFrequency = 49.9 HERTZ
2024-11-16T09:12:59.999+01:00 ERROR 1 --- [   scheduling-8] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.lang.NoSuchMethodError: 'double java.util.Random.nextDouble(double, double)'
	at de.wyraz.homedatabroker.source.DummySource.schedule(DummySource.java:48) ~[classes!/:1.0.0-SNAPSHOT]
	at de.wyraz.homedatabroker.source.DummySource.lambda$start$0(DummySource.java:40) ~[classes!/:1.0.0-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.9.jar!/:6.0.9]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96) ~[spring-context-6.0.9.jar!/:6.0.9]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
2024-11-16T09:13:00.125+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.energyImportTotal = 447696.8 WATT_HOUR
2024-11-16T09:13:00.125+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.energyExportTotal = 1457853.8 WATT_HOUR
2024-11-16T09:13:00.125+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.powerTotal = 28 WATT
2024-11-16T09:13:00.125+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.powerL1 = 63 WATT
2024-11-16T09:13:00.126+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.powerL2 = -103 WATT
2024-11-16T09:13:00.126+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.powerL3 = 66 WATT
2024-11-16T09:13:00.126+01:00 DEBUG 1 --- [  scheduling-16] d.w.h.metric.MetricRegistry              : pulse.voltageL1 = 233.7 VOLT
`

**Comment by micw** [comment]
What's the java version? Seems that is a method of the interface java.util.random.RandomGenerator which was introduced in java 17.

**Comment by hubecker** [comment]
/app # java -version
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+14)
OpenJDK 64-Bit Server VM (build 17-ea+14, mixed mode, sharing)
/app # 

i am using the following image:
`ghcr.io/micw/homedatabroker:master`
