### ISSUE TITLE
MQTTdata cannot be read out anymore

### ISSUE THREAD

**Issue by Clanchef** [micw/homedatabroker#6]
Something went wrong during the update yesterday. The "old" tibber-pulse-reader" works but homedatabroker not anymore

```
2023-09-03T07:05:36.109+02:00  WARN 1 --- [   scheduling-8] d.w.h.s.TibberPulseHttpSource.pulse      : Unable to fetch data from tibber pulse bridge

java.lang.NullPointerException: Cannot invoke "com.hivemq.client.mqtt.mqtt3.Mqtt3AsyncClient.publishWith()" because "this.mqttClient" is null
        at de.wyraz.homedatabroker.output.MQTTOutput.publishMetric(MQTTOutput.java:102) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.homedatabroker.output.MQTTOutput.publishMetric(MQTTOutput.java:22) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.homedatabroker.metric.MetricSubscription.publishMetric(MetricSubscription.java:22) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.homedatabroker.metric.MetricRegistry.publish(MetricRegistry.java:34) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.homedatabroker.source.AbstractSource.publishMetric(AbstractSource.java:13) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.homedatabroker.source.TibberPulseHttpSource.schedule(TibberPulseHttpSource.java:64) ~[classes!/:1.0.0-SNAPSHOT]
        at de.wyraz.homedatabroker.source.AbstractScheduledSource.lambda$start$0(AbstractScheduledSource.java:20) ~[classes!/:1.0.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.9.jar!/:6.0.9]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96) ~[spring-context-6.0.9.jar!/:6.0.9]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]

```

**Comment by micw** [comment]
Should be fixed now. I have tagged a build v0.3. If this works stable for you, you can switch to the tag so that updates to master do not break your setup anymore.

**Comment by Clanchef** [comment]
Hello mciw, 

thanks for the quick fix ... works again.

best regards,
Martin

**Comment by Clanchef** [comment]
Closed
